services:
  storage:
    image: redis:latest
    volumes:
      - ./data:/data
  counter:
    image: node:latest
    volumes:
      - ./:/app
    ports:
    - 80:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    working_dir: /app
    depends_on:
      - storage
    command: ["npm", "run", "dev"]
  site:
    image: node:latest
    volumes:
      - ../express-library/:/site
    ports:
      - 8080:5000
    environment:
      - PORT=5000
    depends_on:
      - counter
    command: ["npm", "run", "prod"]

